version: '3'

services:

  nginx:
    container_name: photos-nginx
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm
    ports:
      - '8080:80'

  php-fpm:
    container_name: photos-php
    build: Docker/php-fpm
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./node_modules:/var/www/html/node_modules
      - ./public/images:/var/www/html/public/images
      - ./etc/infrastructure/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - rabbitmq
    links:
      - mysql
      - redis

  mysql:
    container_name: photos-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'photosdb'
      MYSQL_USER: 'photos'
      MYSQL_PASSWORD: 'photos'
      MYSQL_ROOT_PASSWORD: 'photos'
    volumes:
      - ./var/mysql:/var/lib/mysql
    ports:
      - '3306:3306'

  redis:
    container_name: photos-redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./var/redis:/data

  rabbitmq:
    container_name: photos-rabbitmq
    build: Docker/rabbitmq
    restart: unless-stopped
    volumes:
      - ./var/rabbitmq/:/var/lib/rabbitmq
    ports:
      - '15674:15672'

  elasticsearch:
    container_name: photos-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    environment:
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - ./var/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'

  kibana:
    container_name: photos-kibana
    image: docker.elastic.co/kibana/kibana:6.7.0
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  blackfire:
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID: '3622b39f-ea96-43e1-b209-9ccbb1e4d575'
      BLACKFIRE_SERVER_TOKEN: '90deddbb5e02a8f9e71395463f7e29a8ccec0d28c342cbf6a74e504f6fab3011'