version: '3'

services:

  nginx:
    container_name: photos-nginx
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    container_name: photos-php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./etc/infrastructure/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    env_file:
      - .env
    links:
      - mysql
      - redis

  mysql:
    container_name: photos-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'photosdb'
      MYSQL_USER: 'photos'
      MYSQL_PASSWORD: 'photos'
      MYSQL_ROOT_PASSWORD: 'photos'
    ports:
      - '3306:3306'
    volumes:
      - ./var/mysql:/var/lib/mysql

  redis:
    container_name: photos-redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./var/redis:/data

  rabbitmq:
    container_name: photos-rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: 'photos'
      RABBITMQ_DEFAULT_PASS: 'photos'
    volumes:
      - ./var/rabbitmq/:/var/lib/rabbitmq
    ports:
      - '5630:5672'
      - '15630:15672'
