version: '3'

services:

  nginx:
    container_name: photos-nginx
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./etc/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    links:
      - php-fpm
    ports:
      - '8080:80'

  php-fpm:
    container_name: photos-php
    build: Docker/php-fpm
    volumes:
      - .:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./public/images:/var/www/html/public/images
      - ./etc/infrastructure/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - rabbitmq
    links:
      - mysql
      - redis

  mysql:
    container_name: photos-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'photosdb'
      MYSQL_USER: 'photos'
      MYSQL_PASSWORD: 'photos'
      MYSQL_ROOT_PASSWORD: 'photos'
    volumes:
      - ./var/mysql:/var/lib/mysql
    ports:
      - '3306:3306'

  redis:
    container_name: photos-redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./var/redis:/data

  rabbitmq:
    container_name: photos-rabbitmq
    build: Docker/rabbitmq
    restart: unless-stopped
    volumes:
      - ./var/rabbitmq/:/var/lib/rabbitmq
    ports:
      - '15674:15672'
