parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Photos\File\Infrastructure\Controller\:
       resource: '../src/Photos/File/Infrastructure/Controller'
       tags: ['controller.service_arguments']